### ISSUE TITLE
需求申请

### ISSUE THREAD

**Issue by liyusu-tsinghua** [clipber/kuaitie#124]
**平台**
e.g: Android | Windows

**需求描述**
捐赠平台能不能放个支付宝或者淘宝啊？

**解决了您的什么问题?**
我想捐赠但是我没有PayPal

**附言**
我也就捐个6.66或者8.88，要是作者并不想传收款码就算了

**Comment by cissusnar** [comment]
捐赠随缘，心意到了就好啦：）
