### ISSUE TITLE
win11 无法连接服务器

### ISSUE THREAD

**Issue by denghz** [clipber/kuaitie#128]
**BUG描述**
无法连接服务器同步剪贴板
**如何复现**
1. 
2. 
3. 

**截屏**

<img width="360" alt="image" src="https://user-images.githubusercontent.com/33660196/155969051-086a836b-4b34-4037-95e8-dbebb2b9e78d.png">

**桌面版:**
 - 系统版本:
 - Edition	Windows 11 Pro
Version	21H2
Installed on	‎1/‎30/‎2022
OS build	22000.493
Experience	Windows Feature Experience Pack 1000.22000.493.0

 - 快贴版本 2.2

**手机版:**
 - 设备: [e.g. iPhone6 | pixel 3a]
 - 系统版本: [e.g. iOS8.1 | Android 8]
 - 快贴版本 [e.g. 2.1.1]

**附言**
...

**Comment by dasiweitamiao** [comment]
一样用不了

**Comment by cissusnar** [comment]
证书过期了忘记renew了，已修复

**Comment by dasiweitamiao** [comment]
非常感谢
