### ISSUE TITLE
报告BUG

### ISSUE THREAD

**Issue by forzwj** [clipber/kuaitie#133]
**BUG描述**
Android miui13

**如何复现**
1. 登陆无效
2. 登陆后待机后会变成无登陆状态
3. 

**截屏**

**桌面版:**
 - 系统版本: [e.g. macOS 10.15 | Windows 10 build 1883]
 - 快贴版本 [e.g. 2.1.0]

**手机版:**
 - 设备: [e.g. iPhone6 | pixel 3a]  xiaomi12
 - 系统版本: [e.g. iOS8.1 | Android 8]  Android 10
 - 快贴版本 [e.g. 2.1.1]  3.0.3

**附言**
...

**Comment by cissusnar** [comment]
问题已经找到了, 下周的版本修复下. 

主要问题在于设备id的问题, 很早的一段代码取了一个Secure.ANDROID_ID, 正常系统会返回一个唯一值, 但小米最近的系统, 会返回一个0000000000000000, 我这里只判断了返回空, 所以就导致一些小米设备的设备ID重复了. 

目前只有小米系统存在这个问题, 下个版本更新后会对这个做一下处理

**Comment by cissusnar** [comment]
3.0.4已修复
