### ISSUE TITLE
增加自动删除空格插件

### ISSUE THREAD

**Issue by appw-cn** [clipber/kuaitie#134]
**平台**
Mac OS 10.15.7

**需求描述**
一个插件，删除文本中所有空格。

**解决了您的什么问题?**
经常需要从PDF文件中，复制出文字，放到笔记中。由于PDF的排版原因，文字总包含很多空格。逼死强迫症，总要手动去删除。

**附言**
如果方便的话，希望可以实现这个功能。如果太麻烦，就算了。
谢谢开发者，提供这么优秀的软件。

**Comment by cissusnar** [comment]
这个并不是很难, 我可以抽空写一个 
其实你也可以自己看一下lua语言, 试着写一下, 这样更有成就刚 :)

**Comment by appw-cn** [comment]
唉呀，转了一圈，又回来了。
请问在哪里可以看lua语言呢？我试试看吧…

**Comment by cissusnar** [comment]
https://github.com/cissusnar/cpluginscript/blob/master/remove_spaces.cplugin/main.lua
刚刚写了一个删除文本内空格的插件. 可以参考下 :) 

你这里应该类似于: 
`
local app = require("app")

function urlencode(str)
	if (str) then
		str = string.gsub (str, "１", "1")
		str = str.gsub (str, "２", "2")
		str = str.gsub (str, "３", "3")
		str = str.gsub (str, "４", "4")
		str = str.gsub (str, "５", "5")
		str = str.gsub (str, "６", "6")
		str = str.gsub (str, "７", "7")
		str = str.gsub (str, "８", "8")
		str = str.gsub (str, "９", "9")
		str = str.gsub (str, "０", "0")
	end
	return str
end
`

**Comment by appw-cn** [comment]
居然可以这么简洁👍🏻👍🏻👍🏻
```
return text:gsub(" ", "")
```
谢谢哦~ 应该按照Payload\plugname.cplugin进行打包成zip文件，还可以使用了吧？

**Comment by cissusnar** [comment]
如果是mac的话, 直接使用 
`
./cpkgen.sh -p remove_spaces
`
如果是Windows可能比较麻烦. 
可以使用我刚刚打包的(解压成[.cpk]使用)  :)


[remove_spaces.cpk.zip](https://github.com/clipber/kuaitie/files/9198665/remove_spaces.cpk.zip)

**Comment by appw-cn** [comment]
安装成功，效果很惊艳呢！

我是mac，但是那个代码也不太会，所以使用了这个压缩包。
> [remove_spaces.cpk.zip](https://github.com/clipber/kuaitie/files/9198665/remove_spaces.cpk.zip)

感谢，好人一生平安~

**Comment by appw-cn** [comment]
安装成功，效果很惊艳呢！

我是mac，但是那个代码也不太会，所以使用了这个压缩包。

[remove_spaces.cpk.zip](https://github.com/clipber/kuaitie/files/9198665/remove_spaces.cpk.zip)

感谢，好人一生平安~
