### ISSUE TITLE
报告BUG

### ISSUE THREAD

**Issue by Darkluna999** [clipber/kuaitie#142]
**BUG描述**

闪退或弹出debug对话框
![image](https://user-images.githubusercontent.com/53258301/202840527-895ad3ed-c6f0-4fef-8404-98bba5f8712c.png)

**如何复现**
1. 快速多次点击托盘区图标弹出菜单

**截屏**

**桌面版:**
 - 系统版本: win 11 build 25236
 - 快贴版本 3.1.6

**附言**
...

**Comment by cissusnar** [comment]
非常感谢提交bug ：）
这个问题会尽快在下一个小版本中修复

**Comment by cissusnar** [comment]
3.1.8已修复，可以在官网下载3.1.8版本了
