### ISSUE TITLE
很离谱的BUG

### ISSUE THREAD

**Issue by woann** [clipber/kuaitie#149]
**BUG描述**
windows11、iphone14pro(ios16.5.1),登录同一个账号（304550409@qq.com）,不管是在手机还是电脑端复制内容，甚至收藏，都无法同步

**截屏**
粘贴板不同步：
![微信图片_20230708095023](https://github.com/clipber/kuaitie/assets/25681022/65bd9c24-91b1-4596-9a63-e71ae50431b6)
![微信图片_20230708095136](https://github.com/clipber/kuaitie/assets/25681022/8af57a65-2e4d-46c5-a8ae-37da7251acd0)
收藏不同步：
![微信图片_20230708095031](https://github.com/clipber/kuaitie/assets/25681022/ea952b21-cd8a-4426-ac13-6e8b031d8a74)
![微信图片_20230708095218](https://github.com/clipber/kuaitie/assets/25681022/e0c8aee3-0af0-497e-b800-461fdc0fd433)

**桌面版:**
 - 系统版本:windows11
 - 快贴版本3.3.1

**手机版:**
 - 设备:iphone14pro
 - 系统版本:ios16.5.1
 - 快贴版本 3.2.8

**附言**
...

**Comment by woann** [comment]
我甚至在安卓平板也登录了这个账号，依旧任何数据都不同步，什么情况？

**Comment by cissusnar** [comment]
感谢反馈：） 
快贴不是一款开箱即用的产品，使用方法和功能可能需要一定的探索和学习成本。
比如可以点击一下手机端的红色感叹号，来看看有什么提醒 ：）

**Comment by woann** [comment]
Ok，谢谢
