### ISSUE TITLE
报告BUG：取消“自动设置剪贴板”无效

### ISSUE THREAD

**Issue by xxhhlk** [clipber/kuaitie#151]
**BUG描述**
Windows版，设置里的“自动设置剪贴板”取消勾选后，仍然会自动设置……

**如何复现**
1. 取消勾选这项设置
2. 另一台设备随意复制内容
3. 这台设备仍然会自动设置剪贴板

**截屏**
![Snipaste_2023-09-23_00001](https://github.com/clipber/kuaitie/assets/15075327/558632dd-e50d-4ddb-80e6-c02237397586)

**桌面版:**
 - 系统版本: Windows 10 22H2 19045.3448
 - 快贴版本 3.5.0

**附言**
早知道不升级了 官网也没上一个版本的下载（

**Comment by cissusnar** [comment]
感谢反馈，这个问题我会查看一下，在下个版本中修复
