### ISSUE TITLE
报告BUG：关于图片复制与粘贴的问题 @Android客户端

### ISSUE THREAD

**Issue by PianCat** [clipber/kuaitie#154]
**BUG描述**

**如何复现**
1. Android 13 ColorOS 13.1 复制图片会提示无法正确处理图片：
 
![快贴Bug1](https://github.com/clipber/kuaitie/assets/50688679/7a053ead-2b43-43eb-b070-379c5994e4d7)

2. 在部分软件中粘贴来自其他设备剪贴板的设备表现为无效

![快贴Bug2](https://github.com/clipber/kuaitie/assets/50688679/97cdccf1-3298-4da9-994f-202c10263b43)

**截屏**

**桌面版:**
 - 系统版本: Windows 11 23H2
 - 快贴版本 3.6.3

**手机版:**
 - 设备: OnePlus 8 Pro
 - 系统版本: Android 13 ColorOS 13.1
 - 快贴版本 3.6.7

**附言**
...
如GiF所示

**Comment by cissusnar** [comment]
感谢反馈, 图片目前只在原生Android上测试过, 其他分支还没有测试 : (

**Comment by cissusnar** [comment]
快贴设置图片的时候, 会增加一个独立的tag, 这个tag只有快贴自己读取, 但是这个app读取这个tag, 并没有读取图片数据
