### ISSUE TITLE
更新编译工具为34后，Android版闪退

### ISSUE THREAD

**Issue by CberYellowstone** [clipber/kuaitie#156]
系统：ColorOS Android 14
安装途径：Google Play

**Comment by cissusnar** [comment]
修复的版本已经提交了
由于前台服务的权限问题导致的
但是这个被Google拒绝了
正在沟通，如果Google不允许快贴使用前台服务
可能会把前提服务去掉

**Comment by CberYellowstone** [comment]
> 修复的版本已经提交了 由于前台服务的权限问题导致的 但是这个被Google拒绝了 正在沟通，如果Google不允许快贴使用前台服务 可能会把前提服务去掉

修复版可以从某个地方提前获得吗

**Comment by cissusnar** [comment]
可以先等待Google审核通过，应该在明天就有结果

**Comment by cissusnar** [comment]
Google play审核通过了，可以更新修复问题

**Comment by CberYellowstone** [comment]
已解决
